[pytest]
asyncio_mode = auto
testpaths = tests/unit
addopts =
    --cov=custom_components.aigues_de_reus
    --cov-report=term-missing
    --strict-markers
    -ra
    -p no:homeassistant
filterwarnings =
    ignore::DeprecationWarning
